// Auto-generated by LibreLane
module top_module(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[31:0] a,
  input[31:0] b,
  input cin,
  output[31:0] sum,
  output cout
);
endmodule
